//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLS_SLE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentRubric
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssessmentRubric()
        {
            this.Outcomes = new HashSet<Outcome>();
            this.ScoreTypes = new HashSet<ScoreType>();
            this.SectionRubrics = new HashSet<SectionRubric>();
        }
    
        public short RubricID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte AssessmentID { get; set; }
        public Nullable<decimal> OutcomePassRate { get; set; }
        public bool CalculateOutcomePassRate { get; set; }
    
        public virtual Assessment Assessment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Outcome> Outcomes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScoreType> ScoreTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SectionRubric> SectionRubrics { get; set; }
    }
}
