//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLS_SLE.Models
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.Enrollments = new HashSet<Enrollment>();
            this.Sections = new HashSet<Section>();
            this.StudentPrograms = new HashSet<StudentProgram>();
            this.StudentScores = new HashSet<StudentScore>();
        }


        //This is a database identity number, you shouldn't treat it as a students Student ID
        public int PersonID { get; set; }

        [Required(ErrorMessage = "Please include a 9 character student ID number")]
        [StringLength(9, MinimumLength = 9)]
        [RegularExpression(@"^[0-9]*$", ErrorMessage = "A student ID can only be numbers 0, 9")]
        public string IdNumber { get; set; }
        [Required(ErrorMessage = "Please inclulde your first name")]
        [RegularExpression(@"^[A-Za-z]*$", ErrorMessage = "Make sure this field contains only letters, and has no spaces")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Please include your last name")]
        [RegularExpression(@"^[A-Za-z]*$", ErrorMessage = "Make sure this field contains only letters, and has no spaces")]
        public string LastName { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<int> CreatedByLoginID { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public Nullable<int> ModifiedByLoginID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enrollment> Enrollments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Section> Sections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentProgram> StudentPrograms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentScore> StudentScores { get; set; }
        public virtual User User { get; set; }
    }
}
