//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLS_SLE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramSecurityByUser
    {
        public int PersonID { get; set; }
        public string Login { get; set; }
        public byte SchoolID { get; set; }
        public string SchoolName { get; set; }
        public short DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public string DepartmentNumber { get; set; }
        public short ProgramID { get; set; }
        public string ProgramName { get; set; }
        public string ProgramNumber { get; set; }
        public Nullable<byte> CanEditProgramInformation { get; set; }
    }
}
