//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLS_SLE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramDepartment
    {
        public short ProgramDepartmentID { get; set; }
        public short ProgramID { get; set; }
        public short DepartmentID { get; set; }
    }
}
