//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLS_SLE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RubricDetail
    {
        public string AssessmentName { get; set; }
        public short RubricID { get; set; }
        public string RubricName { get; set; }
        public string Description { get; set; }
        public string OutcomeName { get; set; }
        public byte OutcomeSortOrder { get; set; }
        public short CriteriaID { get; set; }
        public string CriteriaName { get; set; }
        public string ExampleText { get; set; }
        public byte CriteriaSortOrder { get; set; }
    }
}
