//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLS_SLE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoreType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScoreType()
        {
            this.StudentScores = new HashSet<StudentScore>();
        }
    
        public short ScoreTypeID { get; set; }
        public short RubricID { get; set; }
        public string Description { get; set; }
        public byte Value { get; set; }
        public byte SortOrder { get; set; }
        public bool IsUnassessedScore { get; set; }
    
        public virtual AssessmentRubric AssessmentRubric { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentScore> StudentScores { get; set; }
    }
}
