
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CLS_SLE.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SectionEnrollment
{

    public int sectionID { get; set; }

    public long EnrollmentID { get; set; }

    public string StudentID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

}

}
