//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLS_SLE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentScoreCount
    {
        public int SectionID { get; set; }
        public short RubricID { get; set; }
        public int StudentID { get; set; }
        public long EnrollmentID { get; set; }
        public Nullable<int> CompletedCount { get; set; }
        public Nullable<int> CriteriaCount { get; set; }
    }
}
