//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLS_SLE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_studentroster
    {
        public string STD_ID { get; set; }
        public string TERM_CODE { get; set; }
        public int CRN { get; set; }
        public string STATUS_CODE { get; set; }
        public string STATUS_DESC { get; set; }
        public System.DateTime STATUS_DATE { get; set; }
    }
}
