//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLS_SLE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_offering
    {
        public int TERM { get; set; }
        public string OFFERING_NO { get; set; }
        public int CRN { get; set; }
        public int FISCAL_YEAR { get; set; }
        public string OFFERING_TITLE { get; set; }
        public string INSTRUCTOR_ID { get; set; }
    }
}
